apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
  name: pi-stock-ddns-update
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pi-stock-ddns-update
  strategy: {}
  template:
    metadata:
      labels:
        name: pi-stock-ddns-update
    spec:
      containers:
        - env:
            - name: PROXIED
              value: "false"
            - name: SUBDOMAIN
              value: "pi"
            - name: ZONE
              value: juli.sh
            - name: CRON
              value: "*/8 * * * *"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: API_KEY
                  name: cloudflare-secret
          image: oznu/cloudflare-ddns:latest
          name: pi-stock-ddns-update
          resources: {}
      restartPolicy: Always
status: {}
