apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik-monitoring
  namespace: kube-system
  labels:
    app: traefik-monitoring
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: traefik
  podMetricsEndpoints:
    - path: /metrics
      port: "metrics"
