apiVersion: v1
data:
  api-token: WHh2Tm5wdzV6TG05RlowQ0NkektvN1VvNTBweThSOWJtbGdFSm81Ng==
kind: Secret
metadata:
  annotations:
    fluentbit.io/exclude: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"api-token":"WHh2Tm5wdzV6TG05RlowQ0NkektvN1VvNTBweThSOWJtbGdFSm81Ng=="},"kind":"Secret","metadata":{"annotations":{"fluentbit.io/exclude":"true"},"name":"cloudflare","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2021-12-27T14:51:08Z"
  name: cloudflare
  namespace: cert-manager

  resourceVersion: "1043603"
  uid: e5b02cad-85e7-4274-90ba-ea9b8a8947ca
type: Opaque
