apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: ju-fa-beck@t-online.de
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-cloudflare
    solvers:
      - dns01:
          cloudflare:
            email: ju-fa-beck@t-online.de
            apiTokenSecretRef:
              name: cloudflare
              key: api-token
