apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: podsync-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50Gi
status: {}
