apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications

configMapGenerator:
  - name: podsync-config
    files:
      - secrets/config.toml

resources:
  - service.yaml
  - claim.yaml
  - deployment.yaml
  - ingress.yaml

