apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - traefik

secretGenerator:
  - name: traefik
    envs:
      - secrets/traefik
  - name: basic-auth
    envs:
      - secrets/basic-auth
    options:
      disableNameSuffixHash: true

configMapGenerator:
  - name: traefik
    files:
      - config/traefik/traefik.yaml
      - config/traefik/middleware.yaml
