apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: https
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: plausible
spec:
  rules:
    - host: hello.home.juli.sh
      http:
        paths:
          - backend:
              service:
                name: plausible
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - hello.home.juli.sh
      secretName: plausible-tls
status:
  loadBalancer: {}

