apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plausible


secretGenerator:
  - name: plausible
    envs:
      - secrets/plausible



resources:
  - clickhouse.yaml
  - deployment.yaml
  - ingress.yaml
  - postgres.yaml
  - service.yaml
